# Generated by Django 5.0.7 on 2025-09-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='therapists/photos/')),
                ('licenses', models.CharField(blank=True, help_text='Comma-separated license acronyms, e.g., LCSW, LMFT', max_length=255)),
                ('npi_number', models.CharField(blank=True, max_length=20)),
                ('specialties', models.TextField(blank=True, help_text='Comma-separated specialties (quick MVP)')),
                ('modalities', models.TextField(blank=True, help_text='Comma-separated modalities (quick MVP)')),
                ('bio_html', models.TextField(blank=True)),
                ('accepts_new_clients', models.BooleanField(default=True)),
                ('telehealth_only', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
