# Generated by Django 5.0.7 on 2025-09-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TherapyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='intro_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='office_email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='practice_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='practice_website_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='AdditionalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_credential_type', models.CharField(blank=True, choices=[('Membership', 'Membership'), ('License', 'License'), ('Certificate', 'Certificate'), ('Degree/Diploma', 'Degree/Diploma')], default='', max_length=16)),
                ('organization_name', models.CharField(max_length=64)),
                ('id_number', models.CharField(blank=True, max_length=32)),
                ('year_issued', models.CharField(max_length=4)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_credentials', to='profiles.therapistprofile')),
            ],
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='age_groups',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='profiles.agegroup'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=128)),
                ('degree_diploma', models.CharField(max_length=64)),
                ('year_graduated', models.CharField(max_length=4)),
                ('year_began_practice', models.CharField(blank=True, max_length=4)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='therapists/gallery/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='profiles.therapistprofile')),
            ],
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapists', to='profiles.gender'),
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of_network', models.BooleanField(default=False)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_details', to='profiles.therapistprofile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.insuranceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(blank=True, max_length=128)),
                ('street_address', models.CharField(blank=True, max_length=128)),
                ('address_line_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('zip', models.CharField(blank=True, max_length=16)),
                ('hide_address_from_public', models.BooleanField(default=False)),
                ('is_primary_address', models.BooleanField(default=False)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='profiles.therapistprofile')),
            ],
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='participant_types',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='profiles.participanttype'),
        ),
        migrations.CreateModel(
            name='PaymentMethodSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.paymentmethod')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_payment_methods', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_top_specialty', models.BooleanField(default=False)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_items', to='profiles.therapistprofile')),
                ('specialty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.specialtylookup')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyTypeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_of_therapy', to='profiles.therapistprofile')),
                ('therapy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.therapytype')),
            ],
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='title_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapists', to='profiles.title'),
        ),
    ]
