# Generated by Django 5.0.7 on 2025-09-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_agegroup_gender_insuranceprovider_participanttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='by_appointment_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, help_text='Two-letter state code (e.g., CA)', max_length=2)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_expires', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses_details', to='profiles.therapistprofile')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='profiles.licensetype')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='profiles.location')),
            ],
            options={
                'ordering': ['location', 'day_of_week', 'start_time'],
                'unique_together': {('location', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
