# Generated by Django 5.0.7 on 2025-09-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_licensetype_location_by_appointment_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LGBTQIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceEthnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=48)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='officehour',
            old_name='start_time',
            new_name='start_time_1',
        ),
        migrations.RenameField(
            model_name='officehour',
            old_name='end_time',
            new_name='end_time_1',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='officehour',
            name='by_appointment_only',
            field=models.BooleanField(default=False, help_text="Ignore times; display 'By appointment' if true"),
        ),
        migrations.AddField(
            model_name='officehour',
            name='start_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officehour',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=Mon .. 6=Sun'),
        ),
        migrations.AlterModelOptions(
            name='officehour',
            options={'ordering': ['location', 'weekday']},
        ),
        migrations.AlterUniqueTogether(
            name='officehour',
            unique_together={('location', 'weekday')},
        ),
        migrations.CreateModel(
            name='AreasOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=32)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_expertise', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='profiles.licensetype')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FaithSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.faith')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faiths', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LGBTQIASelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgbtqia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.lgbtqia')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgbtqia_identities', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict, null=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_verification_logs', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OtherIdentitySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.otheridentity')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_identities', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OtherTherapyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_type', models.CharField(max_length=64)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_therapy_types', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OtherTreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=64)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_treatment_options', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('malpractice_carrier', models.CharField(blank=True, max_length=64)),
                ('malpractice_expiration_date', models.CharField(blank=True, max_length=7)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_insurances', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RaceEthnicitySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.raceethnicity')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_ethnicities', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StateLicenseBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('board_name', models.CharField(blank=True, max_length=128)),
                ('license_type', models.CharField(blank=True, help_text='Optional license type scope if board differs by type', max_length=64)),
                ('search_url', models.CharField(help_text='Public search or lookup URL for manual + automated verification', max_length=512)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'license_type'],
                'unique_together': {('state', 'license_type', 'search_url')},
            },
        ),
        migrations.CreateModel(
            name='TestingTypeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.testingtype')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_types', to='profiles.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='therapists/video_gallery/')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_gallery', to='profiles.therapistprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='officehour',
            name='day_of_week',
        ),
    ]
