# Generated by Django 5.0.7 on 2025-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_seo_description_page_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_image_url',
            field=models.URLField(blank=True, help_text='Absolute URL for social share image (og:image). Leave blank to use default.'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Overrides meta description if set', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_image_url',
            field=models.URLField(blank=True, help_text='Absolute URL for social share image (og:image). Leave blank to use default.'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords (optional; most search engines ignore this)', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Overrides <title> if set', max_length=255),
        ),
    ]
