# Generated by Django 5.0.7 on 2025-09-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_seo_image_url_post_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Overrides the page title tag if set', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='publish', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Overrides the post title tag if set', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='publish', max_length=50),
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
