# Generated by Django 5.0.7 on 2025-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_model_and_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
